### ISSUE TITLE
Hello world unresolved import `std::error::FromError`

### ISSUE THREAD

**Issue by sshquack** [nickel-org/nickel.rs#178]
Hello,

While running the ``hello_world.rs`` an unresolved import error is raised against today's ``rust 1.0.0-beta`` release. Here are the steps to reproduce this issue.

```
$ rustc --version
rustc 1.0.0-dev (built 2015-04-03)

$ cargo --version
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-04-01)

$ git clone --recursive https://github.com/nickel-org/nickel.git && cd nickel

$ cat -n Cargo.toml | sed '19,22!d'
    19
    20  [dependencies.rust-mustache]
    21  git = "https://github.com/nickel-org/rust-mustache.git"
    22

$ cargo clean && cargo update && cargo build
   ...
   ...
   ...
   Compiling rust-mustache v0.3.0 (https://github.com/nickel-org/rust-mustache.git#ce0c1880)
   Compiling url v0.2.29
/Users/om/.cargo/git/checkouts/rust-mustache-b850d4795ca6321d/master/src/encoder.rs:4:5: 4:26 error: unresolved import `std::error::FromError`. There is no `FromError` in `std::error`
/Users/om/.cargo/git/checkouts/rust-mustache-b850d4795ca6321d/master/src/encoder.rs:4 use std::error::FromError;
                                                                                          ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error

$ echo $?
101
```

Since the change corresponding to this line was introduced in https://github.com/nickel-org/rust-mustache/commit/748d9036cf7c488bd9b295e418679da778a590e4 I tried adding ``rev = "1fec611e5878ad01546602ab650357d50f8a1f66"`` (which is the commit before) in ``Cargo.toml``. It results in a different error which is resolved in ``master``.

```
$ cat -n Cargo.toml | sed '19,22!d'
    19
    20  [dependencies.rust-mustache]
    21  git = "https://github.com/nickel-org/rust-mustache.git"
    22  rev = "1fec611e5878ad01546602ab650357d50f8a1f66"
```

I'm pretty new to ``rust``. Any pointers to fix this would be helpful. Thanks for your time in advance!

**Comment by Ryman** [comment]
Should be working now, feel free to reopen if issues persist!

**Comment by sshquack** [comment]
@Ryman Wow - thank you for fixing it ``rust`` fast! It works great now.
